[package]
name = "node"
version = "0.2.0"
edition = "2021"
authors = ["Adithya Bhat <dth.bht@gmail.com>"]

[[bin]]
name = "node"
path = "src/main.rs"

[[bin]]
name = "node-zeus"
path = "src/bin/zeus.rs"

[[bin]]
name = "node-hera"
path = "src/bin/hera.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0"
log4rs = "1"
anyhow = "1"
consensus = { package = "leto", path = "../consensus" }
signal-hook = "0"
serde_json = "1"
fnv = "1"
serde = "1"
bincode = "1"
base64 = "0"
fdlimit = "0.3"

[dependencies.clap]
version = "4"
features = ["derive"]

[dependencies.tokio]
version = "1"
features = [
    "full",
]

[dependencies.mempool]
package = "libmempool-rs"
git = "https://github.com/libdist-rs/libmempool-rs.git"

[dependencies.crypto]
package = "libcrypto"
git = "https://github.com/libdist-rs/libcrypto-rs.git"

[dependencies.net-common]
package = "common"
git = "https://github.com/libdist-rs/libnet-rs.git"

[features]
benchmark = ["consensus/benchmark"]

[profile.release]
debug = 1