"""Deployment — local tmux + remote SSH.

Local mode: spawns N nodes + M clients in tmux windows on this host.
Remote mode: uses fabric.Connection.run over SSH to start binaries on
provisioned AWS hosts.

The two modes share the per-protocol command construction so behaviour
is identical at the binary-invocation level — only the launcher differs.
"""

from __future__ import annotations

import shlex
import subprocess
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

from orchestrator.protocols import Protocol


# ---------------------------------------------------------------------------
# Local tmux launcher
# ---------------------------------------------------------------------------


@dataclass
class LocalProcess:
    """One launched process under the local tmux session."""

    tmux_window: str
    log_path: Path
    pid_file: Optional[Path] = None


def _tmux(args: list[str]) -> None:
    """Best-effort tmux invocation."""
    subprocess.run(["tmux", *args], check=False)


def kill_session(session: str = "leto-bench") -> None:
    """Tear down any prior tmux session with the same name.

    Also pkills lingering protocol processes so port binds succeed on
    the next launch (tmux window kill doesn't propagate to child
    processes reliably on macOS).  Covers every binary the orchestrator
    spawns: leto-rs node/node-zeus + libapollo-rs apollo/artemis.
    """
    _tmux(["kill-session", "-t", session])
    for pattern in (
        "target/release/node ",
        "target/release/node-zeus ",
        "target/release/node-apollo ",
        "target/release/client-apollo ",
        "target/release/node-artemis ",
        "target/release/client-artemis ",
        "target/release/mysticeti ",
        "target/release/mysticeti-dpbridge ",
    ):
        subprocess.run(["pkill", "-9", "-f", pattern], check=False)
    time.sleep(0.5)


def launch_local(
    protocol: Protocol,
    config_dir: Path,
    n: int,
    num_clients: int,
    log_dir: Path,
    rate: int,
    total_txs: int,
    window: int,
    session: str = "leto-bench",
    workspace_root: Optional[Path] = None,
) -> list[LocalProcess]:
    """Spawn `n` nodes + `num_clients` clients in tmux windows.

    Returns one LocalProcess per spawned binary. Caller is responsible
    for `kill_session` after the measurement window elapses.

    Assumes `cargo build --release` has already been run; binaries live
    at `<workspace_root>/<protocol.bin_dir>/`.
    """
    log_dir.mkdir(parents=True, exist_ok=True)
    kill_session(session)
    _tmux(["new-session", "-d", "-s", session, "-n", "warmup"])

    if workspace_root is None:
        # Per-protocol workspace discovery:
        # - leto / zeus: this repo (parent of scripts/).
        # - apollo / artemis: dev path ~/Github/libapollo-rs (since the
        #   AWS install_remote layout doesn't apply locally).
        # - everything else: state/repos/<name>/ checkout.
        if protocol.name in ("leto", "zeus"):
            workspace_root = Path(__file__).resolve().parent.parent.parent
        elif protocol.name in ("apollo", "artemis"):
            workspace_root = Path.home() / "Github" / "libapollo-rs"
        else:
            workspace_root = Path(__file__).resolve().parent.parent / "state" / "repos" / protocol.name
    bin_dir = workspace_root / protocol.bin_dir

    processes: list[LocalProcess] = []

    # Per-protocol expected config files.  leto/zeus use a single shared
    # `<name>-server.json`; apollo/artemis use per-node `nodes-<i>.json`
    # generated by genconfig.
    server_config = config_dir / f"{protocol.name}-server.json"
    apollo_ip_file = config_dir / "ip_file"
    apollo_cli_ip_file = config_dir / "cli_ip_file"
    apollo_client_config = config_dir / "client.json"

    # Key files (leto/zeus only): use repo's examples/ as ground truth.
    leto_keys_dir = workspace_root / "examples" if protocol.name in ("leto", "zeus") else None

    for node_id in range(n):
        log_path = log_dir / f"node-{node_id}.log"

        # Per-protocol substitution map.  All keys defined for every
        # protocol so missing-key surface bugs hard during str.format.
        subs: dict[str, str] = {
            "bin_dir": str(bin_dir),
            "id": str(node_id),
            "n": str(n),
            "rate": str(rate),
            "extra": protocol.node_extra_args,
            "config": str(server_config) if server_config.exists() else "",
            "node_config": str(config_dir / f"nodes-{node_id}.json"),
            "ip_file": str(apollo_ip_file),
            "key_file": "",
        }
        if leto_keys_dir is not None:
            kf = leto_keys_dir / f"keys-{node_id}.json"
            if not kf.exists():
                raise FileNotFoundError(
                    f"missing key file {kf}; run "
                    f"`cargo r -p node -- keys -n {n} -o {leto_keys_dir}` first"
                )
            subs["key_file"] = str(kf)

        cmd = protocol.node_run_cmd.format(**subs)
        full = f"{cmd} > {shlex.quote(str(log_path))} 2>&1"
        window_name = f"node-{node_id}"
        _tmux(["new-window", "-t", session, "-n", window_name])
        _tmux(["send-keys", "-t", f"{session}:{window_name}", full, "C-m"])
        processes.append(LocalProcess(tmux_window=window_name, log_path=log_path))

    # Give nodes time to bind ports + complete inter-node TLS
    # handshakes before clients connect. apollo + artemis + zeus all
    # benefit from a longer gap (artemis specifically times out its
    # client if peers aren't reachable in the first ~5s after launch);
    # for leto the cost is just a few seconds of run time.
    time.sleep(8)

    # Per-protocol client count:
    # - apollo/artemis: single closed-loop client by design.
    # - mysticeti: no separate client (node binary self-generates load
    #   via the TPS env var); skip client launches entirely.
    # - leto/zeus: orchestrator-defined num_clients.
    if protocol.name in ("apollo", "artemis"):
        effective_clients = 1
    elif protocol.name == "mysticeti":
        effective_clients = 0
    else:
        effective_clients = num_clients

    for cli_idx in range(effective_clients):
        client_id = n + cli_idx
        log_path = log_dir / f"client-{client_id}.log"

        per_client = config_dir / f"{protocol.name}-client-{client_id}.json"
        subs = {
            "bin_dir": str(bin_dir),
            "id": str(client_id),
            "rate": str(rate),
            "total_txs": str(total_txs),
            "window": str(window),
            "extra": protocol.client_extra_args,
            "config": str(per_client) if per_client.exists() else "",
            "client_config": str(apollo_client_config),
            "cli_ip_file": str(apollo_cli_ip_file),
        }

        cmd = protocol.client_run_cmd.format(**subs)
        full = f"{cmd} > {shlex.quote(str(log_path))} 2>&1"
        window_name = f"client-{client_id}"
        _tmux(["new-window", "-t", session, "-n", window_name])
        _tmux(["send-keys", "-t", f"{session}:{window_name}", full, "C-m"])
        processes.append(LocalProcess(tmux_window=window_name, log_path=log_path))

    # Optional sidecar (Mysticeti's dpbridge).  Scrapes the metrics
    # endpoint of authority 0 (matching the node-0 metrics convention
    # for leto/zeus/apollo/artemis).  Mysticeti's Prometheus port
    # follows: validator i binds 1500 + i for network, 1504 + i for
    # metrics.  Authority 0 → metrics port 1504.
    if protocol.sidecar_run_cmd:
        # Give the validator generators ~15s past their built-in 10s
        # warmup so the histograms have populated bucket counts the
        # bridge can usefully sample.  This roughly matches the
        # orchestrator's warmup window for the chain-style protocols.
        bridges_dir = Path(__file__).resolve().parent.parent / "bridges"
        log_path = log_dir / "sidecar.log"
        metrics_url = "http://127.0.0.1:1504/metrics"
        max_secs = 600  # bridge auto-exits; orchestrator tears down earlier
        cmd = protocol.sidecar_run_cmd.format(
            bridges_dir=bridges_dir,
            metrics_url=metrics_url,
            max_secs=max_secs,
            extra="",
        )
        full = f"{cmd} > {shlex.quote(str(log_path))} 2>&1"
        window_name = "sidecar-0"
        _tmux(["new-window", "-t", session, "-n", window_name])
        _tmux(["send-keys", "-t", f"{session}:{window_name}", full, "C-m"])
        processes.append(LocalProcess(tmux_window=window_name, log_path=log_path))

    return processes


# ---------------------------------------------------------------------------
# Remote SSH launcher (AWS) — fabric-based.
#
# Shape mirrors libapollo-rs/scripts/fabfile.py's proven install / build /
# launch sequence, generalised over the multi-protocol Protocol registry.
#
# Host layout:
#   ~/leto-bench/
#     repos/<protocol_name>/        # cloned ephemeral checkout, pinned SHA
#     bin/<protocol_name>/          # distributed binaries (from node-0 build)
#     run/<protocol_name>/          # per-run config files + key files
#     logs/<protocol_name>/         # per-run stdout/stderr
#
# Idempotency: install + build skip if the right SHA / binary is already
# present. Re-running `fab install` on an existing cluster is safe.
# ---------------------------------------------------------------------------


REMOTE_ROOT = "/home/ec2-user/leto-bench"
REMOTE_USER = "ec2-user"         # Amazon Linux 2023 arm64 default
TMUX_SESSION = "leto-bench"


def _fabric_imports():
    """Import fabric lazily so the rest of deploy.py works without it
    installed (local-tmux mode has no fabric dependency)."""
    from fabric import Connection            # noqa: F401
    import concurrent.futures as cf          # noqa: F401
    return Connection, cf


def _connections(state: dict, ssh_key_path: str) -> list:
    """One fabric Connection per provisioned instance, ordered by role
    then by index. Nodes come first, clients after — matches the
    convention `aws.py` uses when laying out instances.

    The caller is responsible for closing connections (fabric handles
    this implicitly on garbage collection, but explicit `c.close()` is
    safer for long sweeps).
    """
    Connection, _ = _fabric_imports()
    instances = state.get("instances", [])
    if not instances:
        raise RuntimeError(
            "no instances in scripts/state/aws.json; run `fab provision` first"
        )
    # Sort: nodes first (by index), then clients (by index). The aws.py
    # provisioner inserts them in this order, but be defensive.
    nodes = [i for i in instances if i.get("role") == "node"]
    clients = [i for i in instances if i.get("role") == "client"]
    ordered = nodes + clients
    return [
        Connection(
            host=inst["public_ip"],
            user=REMOTE_USER,
            connect_kwargs={"key_filename": ssh_key_path},
        )
        for inst in ordered
    ]


def _run_parallel(conns, cmd: str, warn: bool = False) -> list:
    """Run the same command on every host concurrently. Returns one
    fabric Result per connection in input order.

    Fabric 3 dropped `ThreadingGroup.run` returning a mapping, so we
    use a small ThreadPoolExecutor to fan out + preserve ordering."""
    _, cf = _fabric_imports()
    def _one(c):
        return c.run(cmd, warn=warn, hide=True)
    with cf.ThreadPoolExecutor(max_workers=max(1, len(conns))) as ex:
        return list(ex.map(_one, conns))


def _ensure_remote_layout(conns) -> None:
    """Create ~/leto-bench/{repos,bin,run,logs} on every host."""
    _run_parallel(conns, f"mkdir -p {REMOTE_ROOT}/{{repos,bin,run,logs}}")


# ---------------------------------------------------------------------------
# install_remote — bootstrap host + clone all requested protocols
# ---------------------------------------------------------------------------


def install_remote(
    state: dict,
    protocols: list[Protocol],
    ssh_key_path: str,
) -> None:
    """Idempotent install across every host:

    1. apt install build-essential cmake clang libssl-dev pkg-config
       librocksdb-dev tmux git (only what's missing).
    2. rustup install stable + cargo PATH.
    3. For each requested protocol: git clone + checkout pinned SHA.
       Skip if HEAD already matches.

    Safe to re-run. Surfaces errors per-host as RuntimeError.
    """
    conns = _connections(state, ssh_key_path)
    _ensure_remote_layout(conns)

    # --- system packages (Amazon Linux 2023; dnf-based) ---
    # Matches libapollo-rs's existing bootstrap (fabfile.py:88).
    # No librocksdb-dev — rust-rocksdb vendors its own + builds via cargo.
    dnf_pkgs = (
        "clang clang-devel cmake gcc gcc-c++ git llvm-devel "
        "openssl-devel pkgconfig perl tmux tar zip rsync curl jq"
    )
    print(f"[install] dnf install on {len(conns)} hosts")
    _run_parallel(
        conns,
        f"sudo dnf install -y --allowerasing {dnf_pkgs}",
    )

    # --- rust toolchain ---
    print("[install] rustup (idempotent)")
    _run_parallel(
        conns,
        # -y: no prompts; --default-toolchain stable; skip if rustup already on PATH.
        "command -v rustup >/dev/null 2>&1 || "
        "curl --proto =https --tlsv1.2 -sSf https://sh.rustup.rs "
        "| sh -s -- -y --default-toolchain stable --profile minimal "
        "  --no-modify-path",
    )
    # Ensure cargo on PATH for subsequent commands.
    _run_parallel(conns, "echo 'source $HOME/.cargo/env' >> $HOME/.bashrc || true")

    # --- per-protocol clone + checkout ---
    for proto in protocols:
        target = f"{REMOTE_ROOT}/repos/{proto.name}"
        sha = proto.git_sha
        if sha == "PINME":
            print(f"[install] WARNING: {proto.name} SHA is PINME — using HEAD")
            sha_cmd = "git rev-parse HEAD"
        else:
            sha_cmd = f"git checkout {sha} && git rev-parse HEAD"

        cmd = (
            f"if [ ! -d {target}/.git ]; then "
            f"  git clone --quiet {proto.git_url} {target}; "
            f"fi && cd {target} "
            f"&& git fetch --quiet --tags origin "
            f"&& {sha_cmd}"
        )
        print(f"[install] clone+checkout {proto.name}@{sha}")
        _run_parallel(conns, cmd)


# ---------------------------------------------------------------------------
# build_remote — build on node 0, distribute to all hosts
# ---------------------------------------------------------------------------


def build_remote(
    state: dict,
    protocols: list[Protocol],
    ssh_key_path: str,
) -> None:
    """For each protocol: build on node 0 + distribute binaries to all
    hosts. Identical instance type + AMI across the cluster makes ABI
    compatibility a non-issue.

    The bin dir on each host ends up at ~/leto-bench/bin/<protocol>/.
    """
    conns = _connections(state, ssh_key_path)
    if not conns:
        raise RuntimeError("no hosts")
    c0 = conns[0]
    other = conns[1:]

    for proto in protocols:
        src = f"{REMOTE_ROOT}/repos/{proto.name}"
        bin_dir = f"{REMOTE_ROOT}/bin/{proto.name}"

        print(f"[build] {proto.name} on node 0 (this can take a while)")
        # Source cargo env in the same shell so cargo is on PATH after
        # a fresh rustup install on this connection.
        c0.run(
            f"source $HOME/.cargo/env && cd {src} && {proto.build_cmd}",
            hide=False,
        )

        # Stage binaries into bin/ on node 0, then scp to others.
        # Apollo's binaries live at workspace_root/target/release/<bin>;
        # so does leto-rs. The build_cmd already produced them.
        c0.run(
            f"rm -rf {bin_dir} && mkdir -p {bin_dir} "
            f"&& cp -r {src}/{proto.bin_dir}/* {bin_dir}/ 2>/dev/null || true",
            warn=True,
        )

        if not other:
            continue

        # Tarball + scp + untar is faster than per-file scp at n=61.
        tarball = f"/tmp/{proto.name}-bin.tar.gz"
        c0.run(f"tar czf {tarball} -C {REMOTE_ROOT}/bin {proto.name}")
        local_stage = Path("/tmp") / f"leto-bench-{proto.name}-bin.tar.gz"
        if local_stage.exists():
            local_stage.unlink()
        c0.get(tarball, str(local_stage))
        c0.run(f"rm -f {tarball}")

        print(f"[build] distribute {proto.name} binaries to {len(other)} other hosts")
        _, cf = _fabric_imports()
        def _push(c, local=local_stage):
            c.put(str(local), tarball)
            c.run(
                f"mkdir -p {REMOTE_ROOT}/bin "
                f"&& tar xzf {tarball} -C {REMOTE_ROOT}/bin "
                f"&& rm -f {tarball}"
            )
        with cf.ThreadPoolExecutor(max_workers=max(1, len(other))) as ex:
            list(ex.map(_push, other))
        local_stage.unlink(missing_ok=True)


# ---------------------------------------------------------------------------
# launch_remote — run one sweep on the cluster
# ---------------------------------------------------------------------------


def launch_remote(
    state: dict,
    protocol: Protocol,
    config_dir: Path,
    n: int,
    num_clients: int,
    log_dir: Path,
    rate: int,
    total_txs: int,
    window: int,
    ssh_key_path: str,
    warmup_secs: int = 5,
    measure_secs: int = 30,
) -> None:
    """Launch `n` nodes + `num_clients` clients on the provisioned AWS
    cluster for ONE sweep, wait for warmup + measure, tear down, fetch
    per-host logs into `log_dir`.

    `state` must have at least `n + num_clients` instances (nodes first,
    clients after).
    """
    log_dir.mkdir(parents=True, exist_ok=True)
    conns = _connections(state, ssh_key_path)
    if len(conns) < n + num_clients:
        raise RuntimeError(
            f"provisioned {len(conns)} hosts; need {n + num_clients} "
            f"({n} nodes + {num_clients} clients)"
        )
    node_conns = conns[:n]
    client_conns = conns[n : n + num_clients]

    bin_dir = f"{REMOTE_ROOT}/bin/{protocol.name}"
    run_dir = f"{REMOTE_ROOT}/run/{protocol.name}"
    log_remote = f"{REMOTE_ROOT}/logs/{protocol.name}"

    # --- tear down any prior tmux session on every host ---
    print(f"[launch] killing prior {TMUX_SESSION} sessions")
    _run_parallel(
        conns,
        f"tmux kill-session -t {TMUX_SESSION} 2>/dev/null || true; "
        f"mkdir -p {run_dir} {log_remote}",
    )

    _, cf = _fabric_imports()

    # --- protocol-specific config distribution ---
    # leto/zeus: server.json + per-node keys-{i}.json
    # apollo/artemis: entire genconfig output dir (nodes-*.json, ip_file,
    #   cli_ip_file, client.json, *.pem, …)
    # mysticeti: self-contained dry-run; nothing to push.
    if protocol.name in ("leto", "zeus"):
        server_config = config_dir / f"{protocol.name}-server.json"
        if not server_config.exists():
            raise FileNotFoundError(f"missing server config: {server_config}")

        # Key files: prefer config_dir/keys/, then fall back to the
        # examples/ dir in the local workspace root.
        keys_dir = config_dir / "keys"
        fallback_keys = Path(__file__).resolve().parent.parent.parent / "examples"

        # For n>4 we need more keys than examples/ ships (which has 0-3 only).
        # Generate them on node-0 via the remote binary and pull back.
        max_fallback_key = 3
        if n - 1 > max_fallback_key:
            # Generate keys remotely on node-0, then pull them down.
            keygen_dir = f"{run_dir}/genkeys"
            node_conns[0].run(
                f"mkdir -p {keygen_dir} && "
                f"{bin_dir}/node keys -n {n} -o {keygen_dir}",
                hide=True,
            )
            keys_dir.mkdir(parents=True, exist_ok=True)
            for ki in range(n):
                node_conns[0].get(
                    f"{keygen_dir}/keys-{ki}.json",
                    str(keys_dir / f"keys-{ki}.json"),
                )
            # Also update fallback so the loop below finds them.
            fallback_keys = keys_dir

        def _push_node_files(idx_and_conn):
            i, c = idx_and_conn
            c.put(str(server_config), f"{run_dir}/{protocol.name}-server.json")
            for cand in (
                keys_dir / f"keys-{i}.json",
                fallback_keys / f"keys-{i}.json",
            ):
                if cand.exists():
                    c.put(str(cand), f"{run_dir}/keys-{i}.json")
                    break

        def _push_client_files(idx_and_conn):
            i, c = idx_and_conn
            client_id = n + i
            client_config = config_dir / f"{protocol.name}-client-{client_id}.json"
            if client_config.exists():
                c.put(str(client_config), f"{run_dir}/{protocol.name}-client-{client_id}.json")

        print("[launch] distributing leto/zeus config + keys")
        with cf.ThreadPoolExecutor(max_workers=max(1, len(conns))) as ex:
            list(ex.map(_push_node_files, enumerate(node_conns)))
            list(ex.map(_push_client_files, enumerate(client_conns)))

    elif protocol.name in ("apollo", "artemis"):
        # Push every file genconfig emitted under config_dir to each
        # relevant host:
        #  - nodes-{i}.json + node-{i}.*.pem → node i only
        #  - ip_file, cli_ip_file, root-cert.pem → all nodes + all clients
        #  - client.json + client-0.*.pem → all client hosts
        ip_file = config_dir / "ip_file"
        cli_ip_file = config_dir / "cli_ip_file"
        root_cert = config_dir / "root-cert.pem"
        shared_files = [f for f in (ip_file, cli_ip_file, root_cert) if f.exists()]

        def _push_apollo_node(idx_and_conn):
            i, c = idx_and_conn
            for sf in shared_files:
                c.put(str(sf), f"{run_dir}/{sf.name}")
            node_cfg = config_dir / f"nodes-{i}.json"
            if node_cfg.exists():
                c.put(str(node_cfg), f"{run_dir}/nodes-{i}.json")
            for ext in ("chain.pem", "key.pem"):
                pem = config_dir / f"node-{i}.{ext}"
                if pem.exists():
                    c.put(str(pem), f"{run_dir}/node-{i}.{ext}")

        def _push_apollo_client(idx_and_conn):
            _i, c = idx_and_conn
            for sf in shared_files:
                c.put(str(sf), f"{run_dir}/{sf.name}")
            client_cfg = config_dir / "client.json"
            if client_cfg.exists():
                c.put(str(client_cfg), f"{run_dir}/client.json")
            for ext in ("chain.pem", "key.pem"):
                pem = config_dir / f"client-0.{ext}"
                if pem.exists():
                    c.put(str(pem), f"{run_dir}/client-0.{ext}")

        print("[launch] distributing apollo/artemis genconfig files")
        with cf.ThreadPoolExecutor(max_workers=max(1, len(conns))) as ex:
            list(ex.map(_push_apollo_node, enumerate(node_conns)))
            list(ex.map(_push_apollo_client, enumerate(client_conns)))
    else:
        # mysticeti dry-run: no config files needed.
        print(f"[launch] {protocol.name} is self-contained (no config push)")

    # --- launch nodes in detached tmux ---
    print(f"[launch] starting {n} {protocol.name} nodes")
    for i, c in enumerate(node_conns):
        # Build per-protocol substitution dict with ALL keys that any
        # node_run_cmd template may reference (missing keys surface as
        # KeyError at format time — preferable to silent wrong output).
        node_subs = dict(
            bin_dir=bin_dir,
            config=f"{run_dir}/{protocol.name}-server.json",
            node_config=f"{run_dir}/nodes-{i}.json",
            ip_file=f"{run_dir}/ip_file",
            id=i,
            n=n,
            rate=rate,
            key_file=f"{run_dir}/keys-{i}.json",
            extra=protocol.node_extra_args,
        )
        node_cmd = protocol.node_run_cmd.format(**node_subs)
        log_path = f"{log_remote}/node-{i}.log"
        # tmux -d detaches; the inner bash -c wrap keeps the pipe redirect.
        cmd = (
            f"source $HOME/.cargo/env 2>/dev/null; "
            f"tmux new-session -d -s {TMUX_SESSION} "
            f"-n node-{i} bash -c "
            f"{shlex.quote(node_cmd + ' > ' + log_path + ' 2>&1')}"
        )
        c.run(cmd)

    # Give nodes a moment to bind before launching clients.
    time.sleep(2)

    # --- launch clients ---
    print(f"[launch] starting {num_clients} {protocol.name} clients")
    for i, c in enumerate(client_conns):
        client_id = n + i
        client_cmd = protocol.client_run_cmd.format(
            bin_dir=bin_dir,
            config=f"{run_dir}/{protocol.name}-client-{client_id}.json",
            client_config=f"{run_dir}/client.json",
            cli_ip_file=f"{run_dir}/cli_ip_file",
            id=client_id,
            rate=rate,
            total_txs=total_txs,
            window=window,
            extra=protocol.client_extra_args,
        )
        log_path = f"{log_remote}/client-{client_id}.log"
        cmd = (
            f"source $HOME/.cargo/env 2>/dev/null; "
            f"tmux new-session -d -s {TMUX_SESSION} "
            f"-n client-{client_id} bash -c "
            f"{shlex.quote(client_cmd + ' > ' + log_path + ' 2>&1')}"
        )
        c.run(cmd)

    # --- optional sidecar (Mysticeti dpbridge) on node 0 ---
    if protocol.sidecar_run_cmd:
        sidecar_max_secs = warmup_secs + measure_secs + 60   # grace period
        # Mysticeti dry-run port layout (mysticeti-core/src/config.rs):
        #   network_port  = BENCHMARK_PORT_OFFSET + authority_id   (1500 + i)
        #   metrics_port  = n + network_port                       (n + 1500 + i)
        # For authority 0 with n nodes: metrics_port = 1500 + n.
        mysticeti_metrics_port = 1500 + n
        sidecar_cmd = protocol.sidecar_run_cmd.format(
            bridges_dir=f"{REMOTE_ROOT}/bin/{protocol.name}_dpbridge",
            metrics_url=f"http://127.0.0.1:{mysticeti_metrics_port}/metrics",
            max_secs=sidecar_max_secs,
            extra="",
        )
        sidecar_log = f"{log_remote}/sidecar.log"
        node_conns[0].run(
            f"tmux new-session -d -s {TMUX_SESSION} -n sidecar bash -c "
            f"{shlex.quote(sidecar_cmd + ' > ' + sidecar_log + ' 2>&1')}",
            warn=True,
        )

    # --- wait warmup + measure ---
    total_wait = warmup_secs + measure_secs
    print(f"[launch] waiting {total_wait}s (warmup={warmup_secs} + measure={measure_secs})")
    time.sleep(total_wait)

    # --- tear down ---
    print(f"[launch] tearing down {TMUX_SESSION} sessions")
    _run_parallel(
        conns,
        f"tmux kill-session -t {TMUX_SESSION} 2>/dev/null || true",
        warn=True,
    )

    # --- fetch logs ---
    print(f"[launch] fetching {protocol.name} logs to {log_dir}")
    def _fetch_node_log(idx_and_conn):
        i, c = idx_and_conn
        try:
            c.get(f"{log_remote}/node-{i}.log", str(log_dir / f"node-{i}.log"))
        except Exception as e:
            print(f"  warn: fetch node-{i}.log failed: {e}")

    def _fetch_client_log(idx_and_conn):
        i, c = idx_and_conn
        client_id = n + i
        try:
            c.get(
                f"{log_remote}/client-{client_id}.log",
                str(log_dir / f"client-{client_id}.log"),
            )
        except Exception as e:
            print(f"  warn: fetch client-{client_id}.log failed: {e}")

    with cf.ThreadPoolExecutor(max_workers=max(1, len(conns))) as ex:
        list(ex.map(_fetch_node_log, enumerate(node_conns)))
        list(ex.map(_fetch_client_log, enumerate(client_conns)))

    if protocol.sidecar_run_cmd:
        try:
            node_conns[0].get(
                f"{log_remote}/sidecar.log",
                str(log_dir / "sidecar.log"),
            )
        except Exception as e:
            print(f"  warn: fetch sidecar.log failed: {e}")

    # Close fabric connections.
    for c in conns:
        try:
            c.close()
        except Exception:
            pass
